#config/routes.yaml

# index:
#     path: /
#     controller: App\Controller\DefaultController::indexAction

# projetos:
#     path: /projetos
#     controller: App\Controller\ProjectsController::indexAction

logout:
    path: /logout